language: cpp

dist: xenial
sudo: required

git:
  depth: 3

matrix:
  include:
    - os: windows
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - CC="gcc-7"
        - CXX="g++-7"
      compiler: gcc
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - CC="gcc-8"
        - CXX="g++-8"
      compiler: gcc
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
      env:
        - CC="gcc-9"
        - CXX="g++-9"
      compiler: gcc
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libstdc++-7-dev
      env:
        - CC="clang-7"
        - CXX="clang++-7"
      compiler: clang
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - libstdc++-7-dev
      env:
        - CC="clang-8"
        - CXX="clang++-8"
      compiler: clang
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - libstdc++-7-dev
      env:
        - CC="clang-9"
        - CXX="clang++-9"
      compiler: clang
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - libstdc++-7-dev
      env:
        - CC="clang-10"
        - CXX="clang++-10"
      compiler: clang
    - os: linux
      arch: amd64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-11 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-11
            - libstdc++-7-dev
      env:
        - CC="clang-11"
        - CXX="clang++-11"
      compiler: clang
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode12

install:
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          source travis-ci/install-cmake-3-13.sh
          ;;
        osx)
          brew upgrade cmake
          ;;
        windows)
          choco install mingw cmake
          ;;
      esac

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          export CMAKE_CXX_FLAGS="-DAFFINITY"
          cmake ..
          ;;
        osx)
          cmake ..
          ;;
        windows)
          cmake -G "MinGW Makefiles" ..
          ;;
      esac

script:
  - cmake --build . -j 2
